import { CounterProvider } from '#contexts/counter';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}
