export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
  user,
  action,
}: {
  children: React.ReactNode;
  user: React.ReactNode;
  action: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>auth/layout</div>
        {children}
        <div>{user}</div>
        <div>{action}</div>
        <div>auth/layout</div>
      </body>
    </html>
  );
}
