export const metadata = {
  title: 'Otp',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
  channel,
  manage,
}: {
  children: React.ReactNode;
  channel: React.ReactNode;
  manage: React.ReactNode;
}) {
  return (
    <>
      <div>{channel}</div>
      {children}
      <div>{manage}</div>
    </>
  );
}
